* General
Some general changes to improve QOL using Emacs for me. Usually just modified values that are already built into Emacs.
** Remove tool bar
#+BEGIN_SRC emacs-lisp
  (tool-bar-mode -1)
#+END_SRC
** Remove menu bar
#+BEGIN_SRC emacs-lisp
  (menu-bar-mode -1)
#+END_SRC
** Remove scroll bar
#+BEGIN_SRC emacs-lisp
  (scroll-bar-mode -1)
#+END_SRC
** Show matching parens
#+BEGIN_SRC emacs-lisp
  (show-paren-mode 1)
#+END_SRC
** Move by camelCase
#+BEGIN_SRC emacs-lisp
  (global-subword-mode 1)
#+END_SRC
** Window split and follow
Why oh why does Emacs not switch to the new split window by default? I thank Uncle Dave for this fix:
#+BEGIN_SRC emacs-lisp
  (defun split-and-follow-horizontally ()
    (interactive)
    (split-window-below)
    (balance-windows)
    (other-window 1))
  (global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)

  (defun split-and-follow-vertically ()
    (interactive)
    (split-window-right)
    (balance-windows)
    (other-window 1))
  (global-set-key (kbd "C-x 3") 'split-and-follow-vertically)
#+END_SRC
** Scroll convservatively
Makes it so the screen doesn't jump when I scroll past the bottom of the view
#+BEGIN_SRC emacs-lisp
  (setq scroll-conservatively 100)
#+END_SRC
** Turn off annoying bell
#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function 'ignore)
#+END_SRC
** Highlight current line
#+BEGIN_SRC emacs-lisp
  (global-hl-line-mode t)
#+END_SRC
** Yes or no means y or n
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
** Electric pairs
#+BEGIN_SRC emacs-lisp
  (setq electric-pair-pairs '(
                              (?\{ . ?\})
                              (?\( . ?\))
                              (?\[ . ?\])
                              (?\" . ?\")
                              ))
  (electric-pair-mode t)
#+END_SRC
** Remove auto-saving
#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil)
  (setq auto-save-default nil)
#+END_SRC
** Show line and column number
#+BEGIN_SRC emacs-lisp
  (setq line-number-mode t)
  (setq column-number-mode t)
  (setq-default display-line-numbers 'relative)
#+END_SRC
* Theme and modeline
** Zero-dark theme
A theme that is aesthetically pleasing
#+BEGIN_SRC emacs-lisp
  (use-package zerodark-theme
    :init
    (load-theme 'zerodark t))
#+END_SRC
** All the icons
Make sure to run M-x all-the-icons-install-fonts
#+BEGIN_SRC emacs-lisp
  (use-package all-the-icons)
#+END_SRC
** Doom modeline
A modeline that is aesthetically pleasing
#+BEGIN_SRC emacs-lisp
  (use-package doom-modeline
        :ensure t
        :hook (after-init . doom-modeline-mode))
#+END_SRC
* Terminal
** Set default terminal to bash
#+BEGIN_SRC emacs-lisp
  (defvar my-term-shell "/bin/bash")
  (defadvice ansi-term (before force-bash)
    (interactive (list my-term-shell)))
  (ad-activate 'ansi-term)
#+END_SRC
** Add shortcut to open ansi-term
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "<s-return>") 'ansi-term)
#+END_SRC
** Remove line numbers for terminals and shells
#+BEGIN_SRC emacs-lisp
  (add-hook 'eshell-mode-hook (lambda () (setq-local display-line-numbers nil)))
  (add-hook 'term-mode-hook (lambda () (setq-local display-line-numbers nil)))
#+END_SRC
* Help
Packages and configs that help me with Emacs
** Which-key
#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :init
    (which-key-mode))
#+END_SRC
** General
#+BEGIN_SRC emacs-lisp
  (use-package general :ensure t
      :config
      (general-create-definer my-general-def
	:prefix "SPC"
	:keymaps 'override
	:states '(normal visual emacs))
      ;; Easy shortcuts
      (my-general-def
	;; Windows
	"w" '(:ignore t :which-key "Windows")
	"wm" 'delete-other-windows
	"wd" 'delete-window
	"w/" 'split-and-follow-vertically
	"w-" 'split-and-follow-horizontally

	;; Fun
	"$" '(:ignore t :which-key "Fun")

	;; Files
	"f" '(:ignore t :which-key "Files")

	;; Buffers
	"b" '(:ignore t :which-key "Buffers")
	"bd" 'kill-this-buffer

	;; Applications
	"a" '(:ignore t :which-key "Applications")
	"ad" 'dired))
#+END_SRC
* Org
Any configs and packages relating to Org-mode
** Add elisp src snippet
#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-structure-template-alist
                 '("el" "#+BEGIN_SRC emacs-lisp\n?\n#+END_SRC"))
#+END_SRC
* Text manipulation and navigation
** Evil
Vim keybindings are just too good
*** Import base
#+BEGIN_SRC emacs-lisp
  (use-package evil
    :config (evil-mode))
#+END_SRC
*** Surround
#+BEGIN_SRC emacs-lisp
  (use-package evil-surround
    :config
    (global-evil-surround-mode 1))
#+END_SRC
*** Commentary
#+BEGIN_SRC emacs-lisp
  (use-package evil-commentary
      :config
      (evil-commentary-mode))
#+END_SRC
*** Multiple cursors
#+BEGIN_SRC emacs-lisp
  (use-package evil-mc
    :config
    (global-evil-mc-mode 1))

  (evil-define-key 'visual evil-mc-key-map
    "A" #'evil-mc-make-cursor-in-visual-selection-end
    "I" #'evil-mc-make-cursor-in-visual-selection-beg)
#+END_SRC
** Windmove
Allows easy transition between windows using Shift+Arrows.
#+BEGIN_SRC emacs-lisp
  (use-package windmove
    :config
    (windmove-default-keybindings))
#+END_SRC
*** Make windmove work in Org-Mode
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-shiftup-final-hook 'windmove-up)
  (add-hook 'org-shiftleft-final-hook 'windmove-left)
  (add-hook 'org-shiftdown-final-hook 'windmove-down)
  (add-hook 'org-shiftright-final-hook 'windmove-right)
#+END_SRC
** Avy
#+BEGIN_SRC emacs-lisp
  (use-package avy
    :ensure t
    :config
    (setq avy-background t)
    (my-general-def
      "SPC" 'avy-goto-char))
#+END_SRC
** Auto complete
#+BEGIN_SRC emacs-lisp
  (use-package company
    :config
    (progn
      (global-company-mode)
      (setq company-tooltip-limit 10)
      (setq company-dabbrev-downcase 0)
      (setq company-idle-delay 0)
      (setq company-echo-delay 0)
      (setq company-minimum-prefix-length 2)
      (setq company-require-match nil)
      (setq company-selection-wrap-around t)
      (setq company-tooltip-align-annotations t)
      (setq company-transformers '(company-sort-by-occurrence))
      (define-key company-active-map (kbd "TAB") 'company-complete-common-or-cycle)
      (define-key company-active-map (kbd "<tab>") 'company-complete-common-or-cycle)
      (define-key company-active-map (kbd "S-TAB") 'company-select-previous)))
#+END_SRC
* Version control and projects
** Magit
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :config
    (my-general-def
      "g" '(:ignore t :which-key "Git")
      "gs" 'magit-status 
      "gp" 'magit-pull-from-upstream)
    (add-hook 'with-editor-mode-hook 'evil-insert-state))
#+END_SRC
** Projectile
#+BEGIN_SRC emacs-lisp
  (use-package projectile
      :config
      (my-general-def
	  "p" '(projectile-command-map :which-key "Projectile")))
#+END_SRC
** Helm
#+BEGIN_SRC emacs-lisp
  (use-package helm
      :diminish helm-mode
      :init
	  (progn
	      (require 'helm-config)
	      (setq helm-candidate-number-limit 100)
	      (setq helm-idle-delay 0.0
		  helm-input-idle-delay 0.01
		  helm-yas-display-key-on-candidate t
		  helm-quick-update t
		  helm-M-x-requires-pattern nil
		  helm-ff-skip-boring-files t)
		  (helm-mode))
      :bind
	  (("C-h a" . helm-apropos)
	  ("M-y" . helm-show-kill-ring)
	  ("M-x" . helm-M-x)
	  ("C-x c o" . helm-occur)
	  ("C-x c s" . helm-swoop)
	  ("C-x c y" . helm-yas-complete)
	  ("C-x c Y" . helm-yas-create-snippet-on-region)
	  ("C-x c SPC" . helm-all-mark-rings))
      :config
	  (my-general-def
	    "bb" 'helm-mini
	    "bl" 'helm-buffers-list))

#+END_SRC
* Fun
** Fireplace
#+BEGIN_SRC emacs-lisp
  (use-package fireplace
    :config
    (my-general-def
      "$f" 'fireplace))
#+END_SRC
* Convenience
Functions and bindings that make Emacs easier to use for me
** Save and reload init.el
#+BEGIN_SRC emacs-lisp
  (defun my/reloadinit ()
    (interactive)
    (load-file "~/.emacs.d/init.el"))

  (my-general-def
    "fer" '(my/reloadinit :which-key "reload init.el"))
#+END_SRC
** Save current buffer(s)
#+BEGIN_SRC emacs-lisp
  (my-general-def
    "fs" 'save-buffer
    "fS" 'save-some-buffers)
#+END_SRC
** Open init.el and config.org
#+BEGIN_SRC emacs-lisp
  (defun my/goto-initel ()
    (interactive)
    (find-file "~/.emacs.d/init.el"))

  (defun my/goto-configorg ()
    (interactive)
    (find-file "~/.emacs.d/config.org"))

  (defun my/open-both ()
    (interactive)
    (delete-other-windows)
    (my/goto-initel)
    (split-and-follow-vertically)
    (my/goto-configorg))

  (my-general-def
    "fed" '(my/goto-initel :which-key "init.el")
    "fec" '(my/goto-configorg :which-key "config.org")
    "feb" '(my/open-both :which-key "open both"))
#+END_SRC
** Switch to most recent buffer
#+BEGIN_SRC emacs-lisp
  (defun my/switch-to-last-buffer ()
    (interactive)
    (switch-to-buffer (other-buffer (current-buffer) 1)))

  (my-general-def
    "TAB" '(my/switch-to-last-buffer :which-key "previous buffer"))
#+END_SRC
* Languages
Packages for specific languages
** React/JS
#+BEGIN_SRC emacs-lisp
  (use-package rjsx-mode
    :init (add-to-list 'auto-mode-alist '("\\.js\\'" . rjsx-mode)))
#+END_SRC
** Web
#+BEGIN_SRC emacs-lisp
  (use-package web-mode
    :init (progn
	    (add-to-list 'auto-mode-alist '("\\.jsp\\'" . web-mode))
	    (add-to-list 'auto-mode-alist '("\\.html\\'" . web-mode))))
#+END_SRC
